import Head from 'next/head'
import { Navbar, Carousel } from "@/components"
import abuelo1 from "@/assets/abuelos-temp/abuelos-temp-1.jpg"
import abuelo2 from "@/assets/abuelos-temp/abuelos-temp-2.jpg"
import abuelo3 from "@/assets/abuelos-temp/abuelos-temp-3.jpg"
import abuelo4 from "@/assets/abuelos-temp/abuelos-temp-4.jpg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Hogar Nuevo Renacer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen'>
        <Navbar />
        <Carousel.Slider slides={4} delay={3}>
          <Carousel.HeroBanner className="text-center text-4xl text-white"
            cover={abuelo1}
          >
            Soy un texto
          </Carousel.HeroBanner>
          <Carousel.HeroBanner cover={abuelo2} />
          <Carousel.HeroBanner cover={abuelo3} />
          <Carousel.HeroBanner cover={abuelo4} />
        </Carousel.Slider>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic ipsa dolor aliquam alias magni a recusandae iste pariatur sunt? Blanditiis nam ad cumque magnam ea. Ab exercitationem doloribus velit accusamus!
          Aut ullam mollitia necessitatibus consectetur quasi accusantium tenetur nobis nostrum sequi voluptas temporibus iste vero animi veritatis, quidem, maxime repellat fuga. Saepe repellendus harum nostrum optio, quis ex porro nihil!
          Molestiae nemo rerum iste inventore magnam itaque asperiores adipisci ea unde, obcaecati, fugit hic blanditiis, delectus aperiam eaque culpa atque minus saepe rem. Esse itaque deserunt officia assumenda voluptatum tempora.
          Voluptate, provident perspiciatis sequi aperiam accusamus, sit ea deleniti itaque quod quo soluta, libero voluptatem pariatur fugit nobis architecto qui at perferendis vero culpa. Recusandae non delectus eligendi repellendus libero.
          Eaque ex, ullam dolorum vitae possimus, exercitationem ad fuga at incidunt, nisi quas? Quaerat vel assumenda architecto. Reprehenderit nisi pariatur assumenda aspernatur temporibus cumque deserunt nostrum, iusto nulla sequi cum?
          Illum, cum. Ut mollitia doloremque voluptas obcaecati illum cumque et provident? Dicta culpa unde quis? Debitis esse perspiciatis harum totam rem hic enim distinctio, eligendi sequi. Soluta nulla eveniet dicta?
          Labore earum reprehenderit vitae dolorum corporis, consectetur ipsam impedit est, nihil ipsum praesentium quod rerum quibusdam rem! Minus cum temporibus earum eaque repellat. Nemo aliquid necessitatibus reprehenderit in reiciendis? Modi?
          Vel laboriosam, pariatur consequatur cupiditate consectetur debitis facilis cum itaque iusto quaerat vero iste impedit amet tempora quidem ipsam quasi. Ipsam expedita mollitia quia id eos ipsum esse itaque alias!
          Modi fugiat illum amet, veritatis enim, perferendis natus saepe sed quam fugit, similique repudiandae expedita harum. Aliquid nulla voluptates consequatur, eius nisi voluptatem sed, facilis fuga qui sit voluptas facere.
          Eligendi labore dolore commodi numquam, nostrum earum molestiae laudantium quam, maxime quo expedita? Repellat dolor amet sequi molestias quam maiores atque libero velit eaque in, exercitationem consequatur ex! Possimus, veritatis?
          Praesentium enim doloribus minus exercitationem fugiat incidunt adipisci, ad eos iure. Voluptatibus omnis perspiciatis blanditiis laudantium deserunt praesentium magni saepe odit. Ipsum accusantium repellendus sunt perspiciatis. Corporis accusantium recusandae voluptate.
          Autem cumque quo pariatur aliquid. Facere, minus iusto porro ipsa magni excepturi voluptate alias quasi earum itaque maxime deserunt corrupti similique quidem officiis dolorum vero magnam saepe repudiandae. Obcaecati, aperiam.
          Rerum incidunt libero magni in ipsam cumque optio odio commodi quis? Tempora minima aliquid dolorem dolor itaque earum dicta praesentium, inventore ut quod exercitationem non cum tenetur numquam adipisci quisquam!
          Ab debitis culpa consequatur incidunt natus quod accusantium repellat in? Architecto aliquid distinctio facilis enim suscipit ipsam, cumque veniam ab consectetur hic accusantium unde error, amet deserunt aliquam harum eum.
          Rem blanditiis voluptatem nam non vero qui obcaecati, ipsam labore necessitatibus expedita possimus eligendi ea error sequi perferendis et natus placeat, accusantium optio corporis dolore voluptatum ad. Ut, voluptate voluptates?
          Quam consequuntur, molestias, molestiae cum voluptatem dicta maiores laudantium soluta nam vitae qui unde neque itaque veniam tempora ipsum quasi perspiciatis nostrum. Ad ipsum quasi atque modi quisquam reiciendis corrupti.
          Libero suscipit doloremque explicabo enim repellendus at consectetur, neque debitis eligendi eaque. Sequi deleniti, molestiae maiores impedit ducimus minima saepe sint officia nesciunt in cupiditate vel doloribus cumque nulla dolorem?
          Enim soluta iure, obcaecati itaque placeat corporis libero magni rerum quasi, laudantium, voluptatibus molestias incidunt ut saepe ipsam nostrum fuga consectetur sunt accusantium natus non ipsa omnis distinctio. Perspiciatis, quia.
          Illo sequi, quibusdam a voluptatibus, unde amet voluptatem sit placeat reiciendis, quos quae tempore eligendi nulla dolores cumque necessitatibus assumenda. Temporibus totam esse et nesciunt non voluptate rem, sint quidem?
          Praesentium quae amet deserunt delectus placeat tempore. Amet minima nostrum, iste iusto perferendis exercitationem perspiciatis, illo itaque voluptas, quia temporibus in velit soluta. Nemo, aliquam veritatis ab reiciendis corporis cumque!
          Neque quo tenetur porro reprehenderit ipsum amet eum exercitationem perspiciatis eius enim, voluptate nemo, modi dicta unde nam vitae repellendus nulla beatae nobis vero voluptatibus distinctio obcaecati inventore facere. Iure!
          Tempora commodi dolor consequatur quas expedita alias earum numquam veniam provident voluptas odit corporis fuga vel ex illum sint dicta dolore, voluptatum, soluta fugiat minima sapiente, neque aut esse? Recusandae?
          Veritatis quia in cum vel omnis aliquam. Veniam laboriosam impedit molestias numquam, porro cupiditate odit ad quas, nihil sit reprehenderit cum natus ab cumque eum laborum odio? Fuga, iste cupiditate.
          Quae ullam perspiciatis tenetur? Numquam modi quibusdam ut eveniet, tempora obcaecati reiciendis eos cupiditate nulla! Laudantium, eaque? Eveniet, culpa omnis ex eaque provident vitae eum sapiente consequatur, cumque mollitia animi!
          A, saepe et? Sit repellendus voluptatibus, modi quod repellat labore assumenda sint consequuntur aperiam asperiores fuga qui sapiente dolores possimus quis. Voluptas accusamus dolore labore sunt iusto, libero assumenda alias.
          Accusamus quis quam minima sit, tenetur praesentium deleniti pariatur hic odio expedita eos nam veritatis impedit alias numquam veniam natus blanditiis ipsam, reprehenderit, doloribus suscipit! Exercitationem neque doloremque laboriosam similique.
          Totam, quibusdam consequuntur? Quos aspernatur placeat vitae adipisci rerum sit tempora, quo nobis maxime magni aperiam deleniti, error dolorum. Doloremque obcaecati minus ipsa possimus qui excepturi. Fugit odit ea et?
          A cumque possimus rerum eveniet in recusandae aut expedita vero animi dolorem? Iste quam, optio exercitationem earum voluptatibus sit sint? Omnis impedit fugiat velit numquam? Possimus distinctio culpa incidunt quaerat!
          Architecto non error facere accusantium eaque quaerat aut nisi. Perspiciatis sint sed, est expedita in unde! Animi aut in quasi, minima commodi maiores quaerat, laborum reprehenderit ipsam iusto culpa similique.
          Nemo voluptas officiis cumque itaque at nihil nisi? Vel nesciunt ducimus, error ullam ad libero architecto reprehenderit, fugiat corrupti iure dolorem magnam numquam ipsa id neque officia aspernatur? Nemo, impedit?
          Exercitationem fugiat, dolorem illum repudiandae laudantium fugit officia reprehenderit quis totam odio iure voluptates itaque mollitia dolorum! Animi ex eius dolorum magni doloribus sequi ipsum, dolores maiores quam, voluptas alias?
          Minus odit alias qui corporis necessitatibus velit cumque beatae hic exercitationem! Voluptate nisi vel quasi incidunt, eveniet architecto adipisci ratione praesentium eos ut accusamus tenetur? Nostrum veritatis laboriosam exercitationem cum!
          Eaque minima assumenda alias expedita porro exercitationem iusto commodi reiciendis, veritatis autem pariatur in illum fugit! Quos, aut alias quam consequuntur ducimus officia natus pariatur fugiat qui itaque, reiciendis saepe!
          Rerum omnis impedit deleniti sapiente vitae cupiditate! Unde impedit velit eligendi reiciendis exercitationem ab iusto molestias, atque quo rem. Dicta minus, eos voluptate vel aut unde minima molestias quos autem.
          Esse atque a doloremque ad ratione pariatur ex labore, non expedita debitis, iure hic, nihil at! Natus, quae! Nam totam veniam voluptatum ea consectetur corporis ratione quos qui exercitationem perferendis.
          Mollitia veritatis soluta dignissimos debitis asperiores dolore, fuga, odio aliquam quasi eius itaque similique tempore eveniet explicabo corporis sequi dolor maxime, doloremque neque hic? Voluptatem assumenda magni sint atque rerum.
          Nulla, ab? Magni vel quam consectetur harum illum quo itaque soluta voluptatibus, cum libero ex, ipsum omnis asperiores pariatur voluptas ipsam voluptates sit possimus culpa quibusdam quia placeat minima distinctio.
          Omnis sed laudantium dignissimos, beatae incidunt minima hic placeat ut eaque eos excepturi voluptatem dolorem tempora ex nesciunt distinctio quisquam dolores quod amet accusamus odit iure in. Pariatur, corrupti numquam?
          Labore, quas. Delectus nobis neque sit perspiciatis aperiam, iusto et non. Dignissimos cumque quas laudantium ratione corrupti ea, ipsa aliquam quam, unde velit sunt, nihil beatae quaerat tempora animi natus!
          Minus alias cumque ipsa quisquam nobis omnis asperiores laborum eius corporis, maxime iure ab, porro quasi. Vel, ad vero assumenda est corrupti, facere aperiam commodi, natus praesentium eaque itaque architecto.
          Similique quaerat, recusandae blanditiis fuga consequuntur nisi, mollitia possimus quis rerum sequi expedita eos. Cum enim doloribus, non voluptatum amet rerum quisquam soluta magnam possimus porro ut? Ex, nulla enim?
          Alias ratione, cupiditate commodi earum, quia, aliquam suscipit delectus nesciunt voluptatum incidunt mollitia error autem temporibus consequatur harum ab! Perspiciatis, laboriosam obcaecati! Non provident nihil consequatur sint et quidem nulla!
          Ex et ratione sapiente perferendis possimus provident, doloribus laudantium voluptatem ducimus. Voluptates commodi, officiis iste qui optio aspernatur ipsam eaque neque accusamus incidunt tempora quibusdam architecto molestiae nihil ducimus ipsa.
          Pariatur ab porro similique esse mollitia libero earum ut beatae doloremque quo ullam, recusandae architecto optio maxime nemo, dolore quas, minus voluptas tempora et debitis animi vitae nostrum. Minus, repellendus.
          Nihil consequuntur quidem asperiores nostrum quod rerum fugit repellat? Temporibus fugiat perferendis, consequatur inventore enim, sit id quaerat ipsam aliquam asperiores at quisquam architecto quasi harum. Rerum aliquam omnis iure!
          Autem harum necessitatibus vitae? Suscipit amet iste ipsa illo nisi, maiores similique laboriosam perferendis accusantium! Maiores rem quod in optio magni adipisci? Perspiciatis libero ipsa excepturi saepe modi nihil repellat?
          Nihil earum facilis saepe harum numquam quod mollitia incidunt sequi expedita voluptates fugit recusandae deserunt, tempore enim dolore ullam iusto est animi molestiae vitae deleniti! Iste totam ad perspiciatis quas.
          Asperiores tenetur est atque, maiores quidem modi. Tempore tenetur rerum necessitatibus error blanditiis, impedit quaerat quis voluptas obcaecati voluptatem a exercitationem in beatae corrupti totam mollitia, ullam facere. Inventore, animi!
          Fuga aut, maiores perspiciatis, at ipsam recusandae dolore alias doloremque, error eligendi consequatur repudiandae sunt aliquid iste non reprehenderit vero vitae est eum ipsum obcaecati magni provident? Quisquam, dolore illo.
          Error dolor distinctio asperiores libero laborum veritatis doloribus ab itaque? Inventore amet consectetur non similique esse consequuntur nisi reprehenderit laborum. Consequatur officiis obcaecati deserunt! Ipsum accusantium at voluptatum molestiae reprehenderit?
          At itaque incidunt iste ratione quisquam delectus consequuntur laudantium repudiandae tenetur, amet eligendi laborum quibusdam ipsam iure dicta beatae eos? Tempora quis vel, impedit repellat beatae distinctio voluptatum nulla? Et?
          Deserunt sunt quidem est optio eveniet molestias minima dolore, qui voluptatem perspiciatis ad! Quibusdam delectus nobis dicta minima sint neque fugit quam error sequi, numquam saepe exercitationem unde quisquam sit!
          Quis aliquid, quos eius, accusamus blanditiis recusandae enim libero unde praesentium, vero harum nesciunt magnam voluptates illum temporibus. Voluptatibus incidunt earum in voluptates quis exercitationem porro cupiditate voluptate, repellendus quae!
          In illum obcaecati delectus expedita vero. Eos temporibus ex neque! Facere recusandae ut debitis reprehenderit. Laboriosam unde et excepturi soluta. Cumque minima fugit illo similique facilis perferendis minus facere aspernatur.
          Nam debitis reprehenderit voluptas maiores iusto placeat ducimus quo nobis similique quos earum architecto, molestias quis amet. Quasi nesciunt molestiae mollitia cum dolor nulla ipsum! Unde veritatis incidunt in corporis.
          Esse voluptas, quam est eaque perspiciatis consequatur autem officiis consequuntur aperiam excepturi odit, sequi, delectus provident accusantium! Soluta culpa ut, quos inventore provident maiores deserunt ab ullam excepturi asperiores laudantium.
          Enim alias itaque distinctio error ad blanditiis illo molestias eveniet voluptate veniam earum neque in quaerat quia, consequatur esse, non suscipit est excepturi aut! Mollitia libero officiis ratione in numquam.
          Delectus sit labore, perferendis ipsam tempora voluptatibus corporis fugiat quasi tenetur ducimus, dicta saepe, modi vero veritatis ipsum repellendus excepturi non vitae pariatur natus recusandae inventore! Officia ullam neque obcaecati.
          Perferendis, saepe unde. Temporibus quasi eveniet laudantium animi sit atque dolorem at dolor ipsam aliquid itaque culpa ad provident iusto, non inventore sapiente debitis similique nisi repudiandae. Maxime, ad obcaecati!
          Nam et tempore consectetur voluptatem, suscipit culpa aliquid qui in, accusamus at autem ex nostrum cum illo dolor placeat dolorem, error voluptas nisi dolores sunt. Totam recusandae illo molestiae magni?
          Nemo repellat eum deleniti facere magnam, quia soluta rem praesentium rerum aliquam eaque beatae alias officiis explicabo sapiente. Hic nostrum pariatur mollitia, est consequuntur nihil. Quae deserunt tenetur suscipit non!
          Voluptatum officia quos facilis accusantium dolorem blanditiis voluptas iste autem sunt. Molestiae, voluptate officiis recusandae ipsum ex doloremque, ullam aliquid nihil laudantium quaerat illo aperiam ad velit quasi asperiores? Eaque.
          Cum dolor quaerat reiciendis voluptates laudantium quia saepe eos itaque, natus ratione iste. Alias eligendi, tempore cupiditate adipisci perspiciatis sunt ipsam repellendus quam nemo minus corrupti omnis repudiandae fugiat architecto.
          Adipisci quis nesciunt aliquam non placeat corrupti error ab magni ex, voluptas mollitia suscipit itaque odit debitis eum nam minus? Nemo voluptatum in provident tempora aliquid explicabo vitae autem error.
          Non maiores placeat fugiat repellat nisi laboriosam vitae? Facilis quis aperiam deserunt excepturi deleniti repudiandae accusamus nostrum ipsa, cumque obcaecati tenetur asperiores. Quisquam eius rem natus qui maxime eaque quibusdam?
        </p>
      </main>
    </>
  )
}
