import Head from 'next/head'
import { Navbar } from "@/components"

export default function Home() {
  return (
    <>
      <Head>
        <title>Hogar Nuevo Renacer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen'>
        <Navbar />
      </main>
    </>
  )
}
